//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fornax.Net.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class dictionary {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal dictionary() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Fornax.Net.Properties.dictionary", typeof(dictionary).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4r5e
        ///5h1t
        ///5hit
        ///a55
        ///anal
        ///anus
        ///ar5e
        ///arrse
        ///arse
        ///ass
        ///ass-fucker
        ///asses
        ///assfucker
        ///assfukka
        ///asshole
        ///assholes
        ///asswhole
        ///a_s_s
        ///b!tch
        ///b00bs
        ///b17ch
        ///b1tch
        ///ballbag
        ///balls
        ///ballsack
        ///bastard
        ///beastial
        ///beastiality
        ///bellend
        ///bestial
        ///bestiality
        ///bi+ch
        ///biatch
        ///bitch
        ///bitcher
        ///bitchers
        ///bitches
        ///bitchin
        ///bitching
        ///bloody
        ///blow
        ///job
        ///blowjob
        ///blowjobs
        ///boiolas
        ///bollock
        ///bollok
        ///boner
        ///boob
        ///boobs
        ///booobs
        ///boooobs
        ///booooobs
        ///booooooobs
        ///breasts
        ///buceta
        ///bugger
        ///bum
        ///bunny
        ///fucker
        ///butt
        ///butthole
        ///buttmuch [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string en_blacklist {
            get {
                return ResourceManager.GetString("en_blacklist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1	first
        ///10	tenth
        ///100	hundredth
        ///1000	thousandth
        ///1000000	millionth
        ///1000000000	billionth
        ///11	eleventh
        ///12	twelfth
        ///13	thirteenth
        ///14	fourteenth
        ///15	fifteenth
        ///16	sixteenth
        ///17	seventeenth
        ///18	eighteenth
        ///19	nineteenth
        ///2	second
        ///20	twentieth
        ///200	two-hundredth
        ///21	twenty-first
        ///22	twenty-second
        ///23	twenty-third
        ///24	twenty-fourth
        ///25	twenty-fifth
        ///26	twenty-sixth
        ///27	twenty-seventh
        ///28	twenty-eighth
        ///29	twenty-ninth
        ///3	third
        ///30	thirtieth
        ///300	three-hundredth
        ///31	thirty-first
        ///32	thirty-second
        ///33	thirty-t [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string en_stem {
            get {
                return ResourceManager.GetString("en_stem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a
        ///able
        ///about
        ///above
        ///abroad
        ///according
        ///accordingly
        ///across
        ///actually
        ///adj
        ///after
        ///afterwards
        ///again
        ///against
        ///ago
        ///ahead
        ///ain&apos;t
        ///all
        ///allow
        ///allows
        ///almost
        ///alone
        ///along
        ///alongside
        ///already
        ///also
        ///although
        ///always
        ///am
        ///amid
        ///amidst
        ///among
        ///amongst
        ///an
        ///and
        ///another
        ///any
        ///anybody
        ///anyhow
        ///anyone
        ///anything
        ///anyway
        ///anyways
        ///anywhere
        ///apart
        ///appear
        ///appreciate
        ///appropriate
        ///are
        ///aren&apos;t
        ///around
        ///as
        ///a&apos;s
        ///aside
        ///ask
        ///asking
        ///associated
        ///at
        ///available
        ///away
        ///awfully
        ///b
        ///back
        ///backward
        ///backwards
        ///be
        ///became
        ///b [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string en_stop {
            get {
                return ResourceManager.GetString("en_stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to abstraction, abstract, abstractedness, generalisation, generalization::
        ///
        ///thing, affair, matter::
        ///
        ///object, aim, objective, target::
        ///
        ///whole, all, altogether, completely, entirely, hale, solid, totally, unanimous, unharmed, unhurt, unit, unscathed, wholly::
        ///
        ///unit, whole::
        ///
        ///congener, congenator, congeneric, relative::
        ///
        ///organism, being::
        ///
        ///being, beingness, existence, organism::
        ///
        ///dwarf, gnome, midget, nanus, overshadow, shadow::
        ///
        ///parent, nurture, raise, rear::
        ///
        ///life, aliveness, animation, biography, lif [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string en_syns {
            get {
                return ResourceManager.GetString("en_syns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a
        ///aa
        ///aaa
        ///aah
        ///aahed
        ///aahing
        ///aahs
        ///aal
        ///aalii
        ///aaliis
        ///aals
        ///aam
        ///aani
        ///aardvark
        ///aardvarks
        ///aardwolf
        ///aardwolves
        ///aargh
        ///aaron
        ///aaronic
        ///aaronical
        ///aaronite
        ///aaronitic
        ///aarrgh
        ///aarrghh
        ///aaru
        ///aas
        ///aasvogel
        ///aasvogels
        ///ab
        ///aba
        ///ababdeh
        ///ababua
        ///abac
        ///abaca
        ///abacay
        ///abacas
        ///abacate
        ///abacaxi
        ///abaci
        ///abacinate
        ///abacination
        ///abacisci
        ///abaciscus
        ///abacist
        ///aback
        ///abacli
        ///abacot
        ///abacterial
        ///abactinal
        ///abactinally
        ///abaction
        ///abactor
        ///abaculi
        ///abaculus
        ///abacus
        ///abacuses
        ///abada
        ///abaddon
        ///abadejo
        ///abadengo
        ///abadia [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string en_voc {
            get {
                return ResourceManager.GetString("en_voc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a	a
        ///Ã	Ã 
        ///abailard	abailard
        ///abaissait	abaiss
        ///abaissant        abaiss
        ///abaisse          abaiss
        ///abaissÃ©          abaiss
        ///abaissement        abaissement
        ///abaissent        abaissent
        ///abaisser         abaiss
        ///abaisserai         abaiss
        ///abandon          abandon
        ///abandonna        abandon
        ///abandonnait        abandon
        ///abandonnant        abandon
        ///abandonne        abandon
        ///abandonnÃ©        abandon
        ///abandonnÃ©e         abandon
        ///abandonner         abandon
        ///abandonnera        abandon
        ///abandonnerait        abandon
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string fr_stem {
            get {
                return ResourceManager.GetString("fr_stem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to alors
        ///au
        ///aucuns
        ///aussi
        ///autre
        ///avant
        ///avec
        ///avoir
        ///bon
        ///car
        ///ce
        ///cela
        ///ces
        ///ceux
        ///chaque
        ///ci
        ///comme
        ///comment
        ///dans
        ///des
        ///du
        ///dedans
        ///dehors
        ///depuis
        ///devrait
        ///doit
        ///donc
        ///dos
        ///début
        ///elle
        ///elles
        ///en
        ///encore
        ///essai
        ///est
        ///et
        ///eu
        ///fait
        ///faites
        ///fois
        ///font
        ///hors
        ///ici
        ///il
        ///ils
        ///je	
        ///juste
        ///la
        ///le
        ///les
        ///leur
        ///là
        ///ma
        ///maintenant
        ///mais
        ///mes
        ///mine
        ///moins
        ///mon
        ///mot
        ///même
        ///ni
        ///nommés
        ///notre
        ///nous
        ///ou
        ///où
        ///par
        ///parce
        ///pas
        ///peut
        ///peu
        ///plupart
        ///pour
        ///pourquoi
        ///quand
        ///que
        ///quel
        ///quelle
        ///quelles
        ///quels
        ///qui
        ///sa
        ///sans
        ///ses [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string fr_stop {
            get {
                return ResourceManager.GetString("fr_stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to | A French stop word list. Comments begin with vertical bar. Each stop
        ///| word is at the start of a line.
        ///
        ///au             |  a + le
        ///aux            |  a + les
        ///avec           |  with
        ///ce             |  this
        ///ces            |  these
        ///dans           |  with
        ///de             |  of
        ///des            |  de + les
        ///du             |  de + le
        ///elle           |  she
        ///en             |  `of them&apos; etc
        ///et             |  and
        ///eux            |  them
        ///il             |  he
        ///je             |  I
        ///la             |  the
        ///le      [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string fr_stop_cnt {
            get {
                return ResourceManager.GetString("fr_stop_cnt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a
        ///Ã 
        ///abailard
        ///abaissait
        ///abaissant
        ///abaisse
        ///abaissÃ©
        ///abaissement
        ///abaissent
        ///abaisser
        ///abaisserai
        ///abandon
        ///abandonna
        ///abandonnait
        ///abandonnant
        ///abandonne
        ///abandonnÃ©
        ///abandonnÃ©e
        ///abandonner
        ///abandonnera
        ///abandonnerait
        ///abandonnÃ©s
        ///abandonnez
        ///abasourdi
        ///abat
        ///abattant
        ///abattement
        ///abattit
        ///abattre
        ///abbaye
        ///abbÃ©
        ///abbÃ©s
        ///abbesse
        ///abeille
        ///abhorrait
        ///abhorre
        ///abhorrÃ©
        ///abÃ®mait
        ///abÃ®me
        ///abÃ®mÃ©
        ///abÃ®mÃ©e
        ///abject
        ///abjurant
        ///ablutions
        ///abnÃ©gation
        ///aboiements
        ///aboiera
        ///abolir
        ///abominable
        ///abominablemen [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string fr_voc {
            get {
                return ResourceManager.GetString("fr_voc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to s(100001740,1,&apos;entity&apos;,n,1,11).
        ///s(100001930,1,&apos;physical entity&apos;,n,1,0).
        ///s(100002137,1,&apos;abstraction&apos;,n,6,0).
        ///s(100002137,2,&apos;abstract entity&apos;,n,1,0).
        ///s(100002452,1,&apos;thing&apos;,n,12,0).
        ///s(100002684,1,&apos;object&apos;,n,1,51).
        ///s(100002684,2,&apos;physical object&apos;,n,1,0).
        ///s(100003553,1,&apos;whole&apos;,n,2,0).
        ///s(100003553,2,&apos;unit&apos;,n,6,0).
        ///s(100003993,1,&apos;congener&apos;,n,3,0).
        ///s(100004258,1,&apos;living thing&apos;,n,1,1).
        ///s(100004258,2,&apos;animate thing&apos;,n,1,0).
        ///s(100004475,1,&apos;organism&apos;,n,1,9).
        ///s(100004475,2,&apos;being&apos;,n,2,6).
        ///s(100005787,1,&apos;benthos&apos;,n,2,0). [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string wn_s {
            get {
                return ResourceManager.GetString("wn_s", resourceCulture);
            }
        }
    }
}
