//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fornax.Net.Lib {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class libraries {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal libraries() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Fornax.Net.Lib.libraries", typeof(libraries).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DCSoft_RTF {
            get {
                object obj = ResourceManager.GetObject("DCSoft_RTF", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] dmach_Mail {
            get {
                object obj = ResourceManager.GetObject("dmach_Mail", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DocumentFormat_OpenXml {
            get {
                object obj = ResourceManager.GetObject("DocumentFormat_OpenXml", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] HtmlAgilityPack {
            get {
                object obj = ResourceManager.GetObject("HtmlAgilityPack", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;doc&gt;
        ///    &lt;assembly&gt;
        ///        &lt;name&gt;HtmlAgilityPack&lt;/name&gt;
        ///    &lt;/assembly&gt;
        ///    &lt;members&gt;
        ///        &lt;member name=&quot;T:HtmlAgilityPack.Crc32&quot;&gt;
        ///            &lt;summary&gt;
        ///            A utility class to compute CRC32.
        ///            &lt;/summary&gt;
        ///        &lt;/member&gt;
        ///        &lt;member name=&quot;M:HtmlAgilityPack.Crc32.CRC32Bytes(System.Byte[])&quot;&gt;
        ///            &lt;summary&gt;
        ///            Compute a checksum for a given array of bytes.
        ///            &lt;/summary&gt;
        ///            &lt;param name=&quot;bytes&quot;&gt;The array of bytes t [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HtmlAgilityPack1 {
            get {
                return ResourceManager.GetString("HtmlAgilityPack1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ICSharpCode_SharpZipLib {
            get {
                object obj = ResourceManager.GetObject("ICSharpCode_SharpZipLib", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;doc&gt;
        ///    &lt;assembly&gt;
        ///        &lt;name&gt;ICSharpCode.SharpZipLib&lt;/name&gt;
        ///    &lt;/assembly&gt;
        ///    &lt;members&gt;
        ///        &lt;member name=&quot;T:ICSharpCode.SharpZipLib.BZip2.BZip2&quot;&gt;
        ///            &lt;summary&gt;
        ///            An example class to demonstrate compression and decompression of BZip2 streams.
        ///            &lt;/summary&gt;
        ///        &lt;/member&gt;
        ///        &lt;member name=&quot;M:ICSharpCode.SharpZipLib.BZip2.BZip2.Decompress(System.IO.Stream,System.IO.Stream,System.Boolean)&quot;&gt;
        ///            &lt;summary&gt;
        ///            Decompr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ICSharpCode_SharpZipLib1 {
            get {
                return ResourceManager.GetString("ICSharpCode_SharpZipLib1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] IKVM_AWT_WinForms {
            get {
                object obj = ResourceManager.GetObject("IKVM_AWT_WinForms", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] IKVM_OpenJDK_Beans {
            get {
                object obj = ResourceManager.GetObject("IKVM_OpenJDK_Beans", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] IKVM_OpenJDK_Charsets {
            get {
                object obj = ResourceManager.GetObject("IKVM_OpenJDK_Charsets", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] IKVM_OpenJDK_Cldrdata {
            get {
                object obj = ResourceManager.GetObject("IKVM_OpenJDK_Cldrdata", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] IKVM_OpenJDK_Corba {
            get {
                object obj = ResourceManager.GetObject("IKVM_OpenJDK_Corba", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] IKVM_OpenJDK_Core {
            get {
                object obj = ResourceManager.GetObject("IKVM_OpenJDK_Core", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] IKVM_OpenJDK_Jdbc {
            get {
                object obj = ResourceManager.GetObject("IKVM_OpenJDK_Jdbc", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] IKVM_OpenJDK_Localedata {
            get {
                object obj = ResourceManager.GetObject("IKVM_OpenJDK_Localedata", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] IKVM_OpenJDK_Management {
            get {
                object obj = ResourceManager.GetObject("IKVM_OpenJDK_Management", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] IKVM_OpenJDK_Media {
            get {
                object obj = ResourceManager.GetObject("IKVM_OpenJDK_Media", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] IKVM_OpenJDK_Misc {
            get {
                object obj = ResourceManager.GetObject("IKVM_OpenJDK_Misc", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] IKVM_OpenJDK_Naming {
            get {
                object obj = ResourceManager.GetObject("IKVM_OpenJDK_Naming", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] IKVM_OpenJDK_Nashorn {
            get {
                object obj = ResourceManager.GetObject("IKVM_OpenJDK_Nashorn", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] IKVM_OpenJDK_Remoting {
            get {
                object obj = ResourceManager.GetObject("IKVM_OpenJDK_Remoting", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] IKVM_OpenJDK_Security {
            get {
                object obj = ResourceManager.GetObject("IKVM_OpenJDK_Security", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] IKVM_OpenJDK_SwingAWT {
            get {
                object obj = ResourceManager.GetObject("IKVM_OpenJDK_SwingAWT", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] IKVM_OpenJDK_Text {
            get {
                object obj = ResourceManager.GetObject("IKVM_OpenJDK_Text", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] IKVM_OpenJDK_Tools {
            get {
                object obj = ResourceManager.GetObject("IKVM_OpenJDK_Tools", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] IKVM_OpenJDK_Util {
            get {
                object obj = ResourceManager.GetObject("IKVM_OpenJDK_Util", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] IKVM_OpenJDK_XML_API {
            get {
                object obj = ResourceManager.GetObject("IKVM_OpenJDK_XML_API", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] IKVM_OpenJDK_XML_Bind {
            get {
                object obj = ResourceManager.GetObject("IKVM_OpenJDK_XML_Bind", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] IKVM_OpenJDK_XML_Crypto {
            get {
                object obj = ResourceManager.GetObject("IKVM_OpenJDK_XML_Crypto", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] IKVM_OpenJDK_XML_Parse {
            get {
                object obj = ResourceManager.GetObject("IKVM_OpenJDK_XML_Parse", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] IKVM_OpenJDK_XML_Transform {
            get {
                object obj = ResourceManager.GetObject("IKVM_OpenJDK_XML_Transform", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] IKVM_OpenJDK_XML_WebServices {
            get {
                object obj = ResourceManager.GetObject("IKVM_OpenJDK_XML_WebServices", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] IKVM_OpenJDK_XML_XPath {
            get {
                object obj = ResourceManager.GetObject("IKVM_OpenJDK_XML_XPath", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] IKVM_Runtime {
            get {
                object obj = ResourceManager.GetObject("IKVM_Runtime", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] IKVM_Runtime_JNI {
            get {
                object obj = ResourceManager.GetObject("IKVM_Runtime_JNI", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] itextsharp {
            get {
                object obj = ResourceManager.GetObject("itextsharp", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;doc&gt;
        ///    &lt;assembly&gt;
        ///        &lt;name&gt;itextsharp&lt;/name&gt;
        ///    &lt;/assembly&gt;
        ///    &lt;members&gt;
        ///        &lt;member name=&quot;T:iTextSharp.text.Anchor&quot;&gt;
        ///            &lt;summary&gt;
        ///            An Anchor can be a reference or a destination of a reference.
        ///            &lt;/summary&gt;
        ///            &lt;remarks&gt;
        ///            An Anchor is a special kind of &lt;see cref=&quot;T:iTextSharp.text.Phrase&quot;/&gt;.
        ///            It is constructed in the same way.
        ///            &lt;/remarks&gt;
        ///            &lt;seealso cref=&quot;T:iTextSharp.text.Eleme [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string iTextSharp1 {
            get {
                return ResourceManager.GetString("iTextSharp1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] LumenWorks_Framework_IO {
            get {
                object obj = ResourceManager.GetObject("LumenWorks_Framework_IO", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;doc&gt;
        ///    &lt;assembly&gt;
        ///        &lt;name&gt;LumenWorks.Framework.IO&lt;/name&gt;
        ///    &lt;/assembly&gt;
        ///    &lt;members&gt;
        ///        &lt;member name=&quot;T:LumenWorks.Framework.IO.Csv.CsvReader&quot;&gt;
        ///            &lt;summary&gt;
        ///            Represents a reader that provides fast, non-cached, forward-only access to CSV data.  
        ///            &lt;/summary&gt;
        ///        &lt;/member&gt;
        ///        &lt;member name=&quot;F:LumenWorks.Framework.IO.Csv.CsvReader.DefaultBufferSize&quot;&gt;
        ///            &lt;summary&gt;
        ///            Defines the default buffer size.
        ///      [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LumenWorks_Framework_IO1 {
            get {
                return ResourceManager.GetString("LumenWorks_Framework_IO1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Lz4Net {
            get {
                object obj = ResourceManager.GetObject("Lz4Net", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;doc&gt;
        ///    &lt;assembly&gt;
        ///        &lt;name&gt;Lz4Net&lt;/name&gt;
        ///    &lt;/assembly&gt;
        ///    &lt;members&gt;
        ///        &lt;member name=&quot;T:Lz4Net.Lz4DecompressionStream&quot;&gt;
        ///            &lt;summary&gt;
        ///            Stream to compress and write back data
        ///            &lt;/summary&gt;
        ///        &lt;/member&gt;
        ///        &lt;member name=&quot;F:Lz4Net.Lz4DecompressionStream.HeaderSize&quot;&gt;
        ///            &lt;summary&gt;
        ///            Room for header
        ///            &lt;/summary&gt;
        ///        &lt;/member&gt;
        ///        &lt;member name=&quot;M:Lz4Net.Lz4DecompressionStream.Flush&quot;&gt;
        ///     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Lz4Net1 {
            get {
                return ResourceManager.GetString("Lz4Net1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Microsoft_Win32_Primitives {
            get {
                object obj = ResourceManager.GetObject("Microsoft_Win32_Primitives", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] MsgReader {
            get {
                object obj = ResourceManager.GetObject("MsgReader", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] NPOI {
            get {
                object obj = ResourceManager.GetObject("NPOI", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] NPOI_OOXML {
            get {
                object obj = ResourceManager.GetObject("NPOI_OOXML", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] NPOI_OpenXml4Net {
            get {
                object obj = ResourceManager.GetObject("NPOI_OpenXml4Net", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] NPOI_OpenXmlFormats {
            get {
                object obj = ResourceManager.GetObject("NPOI_OpenXmlFormats", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] NPOI_ScratchPad_HWPF {
            get {
                object obj = ResourceManager.GetObject("NPOI_ScratchPad_HWPF", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] pdfbox_app_2_0_7 {
            get {
                object obj = ResourceManager.GetObject("pdfbox_app_2_0_7", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;configuration&gt;
        ///   &lt;runtime&gt;
        ///      &lt;assemblyBinding xmlns=&quot;urn:schemas-microsoft-com:asm.v1&quot;&gt;
        ///       &lt;dependentAssembly&gt;
        ///         &lt;assemblyIdentity name=&quot;taglib-sharp&quot; publicKeyToken=&quot;db62eba44689b5b0&quot; /&gt;
        ///         &lt;bindingRedirect oldVersion=&quot;2.0.0.0-2.1.0.0&quot; newVersion=&quot;2.1.0.0&quot;/&gt;
        ///       &lt;/dependentAssembly&gt;
        ///      &lt;/assemblyBinding&gt;
        ///   &lt;/runtime&gt;
        ///&lt;/configuration&gt;
        ///.
        /// </summary>
        internal static string policy_2_0_taglib_sharp {
            get {
                return ResourceManager.GetString("policy_2_0_taglib_sharp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] policy_2_0_taglib_sharp1 {
            get {
                object obj = ResourceManager.GetObject("policy_2_0_taglib_sharp1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] protobuf_net {
            get {
                object obj = ResourceManager.GetObject("protobuf_net", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;doc&gt;
        ///    &lt;assembly&gt;
        ///        &lt;name&gt;protobuf-net&lt;/name&gt;
        ///    &lt;/assembly&gt;
        ///    &lt;members&gt;
        ///        &lt;member name=&quot;T:ProtoBuf.BclHelpers&quot;&gt;
        ///            &lt;summary&gt;
        ///            Provides support for common .NET types that do not have a direct representation
        ///            in protobuf, using the definitions from bcl.proto
        ///            &lt;/summary&gt;
        ///        &lt;/member&gt;
        ///        &lt;member name=&quot;M:ProtoBuf.BclHelpers.GetUninitializedObject(System.Type)&quot;&gt;
        ///            &lt;summary&gt;
        ///            Creates a ne [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string protobuf_net1 {
            get {
                return ResourceManager.GetString("protobuf_net1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] taglib_sharp {
            get {
                object obj = ResourceManager.GetObject("taglib_sharp", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Thought_vCards {
            get {
                object obj = ResourceManager.GetObject("Thought_vCards", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] TikaOnDotNet {
            get {
                object obj = ResourceManager.GetObject("TikaOnDotNet", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] TikaOnDotNet_TextExtraction {
            get {
                object obj = ResourceManager.GetObject("TikaOnDotNet_TextExtraction", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Toxy {
            get {
                object obj = ResourceManager.GetObject("Toxy", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ZeroFormatter {
            get {
                object obj = ResourceManager.GetObject("ZeroFormatter", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ZeroFormatter_Interfaces {
            get {
                object obj = ResourceManager.GetObject("ZeroFormatter_Interfaces", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ZeroFormatterAnalyzer {
            get {
                object obj = ResourceManager.GetObject("ZeroFormatterAnalyzer", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
